// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qforzdhrhbbercegbupe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmb3J6ZGhyaGJiZXJjZWdidXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTMzMjIsImV4cCI6MjA2NTEyOTMyMn0.odu2JpymK1R4MIdZ9Ph2vSz7vzN3KmHr7YQW-fPUIx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);